/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as ComboRouteImport } from './routes/combo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MSlugRouteImport } from './routes/m.$slug'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboRoute = ComboRouteImport.update({
  id: '/combo',
  path: '/combo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combo': typeof ComboRoute
  '/guests': typeof GuestsRoute
  '/memory': typeof MemoryRoute
  '/tracker': typeof TrackerRoute
  '/m/$slug': typeof MSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combo': typeof ComboRoute
  '/guests': typeof GuestsRoute
  '/memory': typeof MemoryRoute
  '/tracker': typeof TrackerRoute
  '/m/$slug': typeof MSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combo': typeof ComboRoute
  '/guests': typeof GuestsRoute
  '/memory': typeof MemoryRoute
  '/tracker': typeof TrackerRoute
  '/m/$slug': typeof MSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combo' | '/guests' | '/memory' | '/tracker' | '/m/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combo' | '/guests' | '/memory' | '/tracker' | '/m/$slug'
  id:
    | '__root__'
    | '/'
    | '/combo'
    | '/guests'
    | '/memory'
    | '/tracker'
    | '/m/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComboRoute: typeof ComboRoute
  GuestsRoute: typeof GuestsRoute
  MemoryRoute: typeof MemoryRoute
  TrackerRoute: typeof TrackerRoute
  MSlugRoute: typeof MSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo': {
      id: '/combo'
      path: '/combo'
      fullPath: '/combo'
      preLoaderRoute: typeof ComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComboRoute: ComboRoute,
  GuestsRoute: GuestsRoute,
  MemoryRoute: MemoryRoute,
  TrackerRoute: TrackerRoute,
  MSlugRoute: MSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
